theme = "rebugo"
baseURL = "https://blog.reb.gg/"
languageCode = "en-us"
title = "rob's blog"
copyright = "Rob Herley"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[params]
  favicon = "images/logo.png"
  readmeRepo = "robherley/robherley"

[[params.social]]
  name = "github"
  link = "https://github.com/robherley"

[[params.social]]
  name = "x"
  link = "https://x.com/robherley"

[[params.social]]
  name = "instagram"
  link = "https://instagram.com/robherley"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/robherley/"

[markup]
  [markup.highlight]
    style = 'catppuccin-frappe'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false

[outputs]
  home = ["HTML", "JSON"]

[privacy]
  [privacy.x]
    enableDNT = true